// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"Janna-IM/app/auth/interface/internal/biz"
	"Janna-IM/app/auth/interface/internal/conf"
	"Janna-IM/app/auth/interface/internal/data"
	"Janna-IM/app/auth/interface/internal/server"
	"Janna-IM/app/auth/interface/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, registry *conf.Registry, confData *conf.Data, auth *conf.Auth, logger log.Logger) (*kratos.App, func(), error) {
	authUseCase := biz.NewAuthUseCase(auth)
	authService := service.NewAuthService(authUseCase, logger)
	grpcServer := server.NewGRPCServer(confServer, authService, logger)
	httpServer := server.NewHTTPServer(confServer, authService, logger)
	registrar := data.NewRegistrar(registry)
	app := newApp(logger, grpcServer, httpServer, registrar)
	return app, func() {
	}, nil
}
