// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "user_id", Type: field.TypeString, Unique: true},
		{Name: "name", Type: field.TypeString},
		{Name: "face_url", Type: field.TypeString},
		{Name: "phone_number", Type: field.TypeString, Size: 32},
		{Name: "email", Type: field.TypeString, Size: 64},
		{Name: "ex", Type: field.TypeString, Size: 1024},
		{Name: "create_ip", Type: field.TypeString, Size: 15},
		{Name: "last_login_ip", Type: field.TypeString, Size: 15},
		{Name: "invitation_code", Type: field.TypeString},
		{Name: "gender", Type: field.TypeInt32},
		{Name: "login_times", Type: field.TypeInt32},
		{Name: "login_limit", Type: field.TypeInt32},
		{Name: "app_manger_level", Type: field.TypeInt32},
		{Name: "global_recv_msg_opt", Type: field.TypeInt32},
		{Name: "status", Type: field.TypeInt32},
		{Name: "birth", Type: field.TypeTime},
		{Name: "create_time", Type: field.TypeTime},
		{Name: "last_login_time", Type: field.TypeTime},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		UsersTable,
	}
)

func init() {
}
