server:
  http:
    addr: 0.0.0.0:8005
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9005
    timeout: 1s
data:
  database:
    driver: mysql
    source: root:localdb001@tcp(127.0.0.1:3306)/janna?parseTime=True
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
